name: 🚀 Building Dev
on:
  push:
    branches:
    - 'dev'

concurrency:
  group: dev-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    name: 🏁 Windows
    uses: ./.github/workflows/client-build-tool.yml
    secrets:
      gcp-secret: ${{ secrets.GCP_TOKEN_BUCKET }}
      cicd-token-github: ${{ secrets.CI_TOKEN_GITHUB }}
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
    with:
      should-deploy: ${{ contains(github.event.head_commit.message, 'version bump to') }}
      should-run-unit-tests: true
      should-notify-on-failure: true
      editor-binary-workflow: windows_builds.yml
      editor-binary-name: MirrorGodotEditorWindows.exe
      editor-binary-download: MirrorGodotEditorWindows.exe
      editor-binary-branch: dev
      editor-template-directory: ~/AppData/Roaming/Godot/export_templates/4.3.dev
      template-binary-workflow: windows_builds.yml
      template-binary-name: windows_release_x86_64.exe
      template-binary-branch: dev
      export-template-file: windows_release_x86_64.exe
      game-environment-cfg-name: dev
      game-export-preset: Windows
      game-binary-name: The Mirror Dev.exe
      bucket-name: mirror_native_client_builds/AutoUpdater
      os: "Windows"
      environment: dev
      url: https://dev-api.themirror.space/storage/clients
      itch-project-name: dev-the-mirror
      platform-file-extension: .zip

  build-linux:
    name: 🐧 Linux
    uses: ./.github/workflows/client-build-tool.yml
    secrets:
      gcp-secret: ${{ secrets.GCP_TOKEN_BUCKET }}
      cicd-token-github: ${{ secrets.CI_TOKEN_GITHUB }}
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
    with:
      should-deploy: ${{ contains(github.event.head_commit.message, 'version bump to') }}
      should-run-unit-tests: true
      should-notify-on-failure: true
      editor-binary-workflow: linux_builds.yml
      editor-binary-name: MirrorGodotEditorLinux.x86_64
      editor-binary-download: MirrorGodotEditorLinux.x86_64
      editor-binary-branch: dev
      editor-template-directory: ~/.local/share/godot/export_templates/4.3.dev
      template-binary-workflow: linux_builds.yml
      template-binary-name: linux_release.x86_64
      template-binary-branch: dev
      export-template-file: linux_release.x86_64
      game-environment-cfg-name: dev
      game-export-preset: Linux
      game-binary-name: The Mirror Dev.x86_64
      bucket-name: mirror_native_client_builds/AutoUpdater
      os: "Linux"
      environment: dev
      url: https://dev-api.themirror.space/storage/clients
      itch-project-name: dev-the-mirror
      platform-file-extension: .zip

  build-macos:
    name: 🍎 MacOS
    uses: ./.github/workflows/client-build-tool.yml
    secrets:
      gcp-secret: ${{ secrets.GCP_TOKEN_BUCKET }}
      cicd-token-github: ${{ secrets.CI_TOKEN_GITHUB }}
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
    with:
      should-deploy: ${{ contains(github.event.head_commit.message, 'version bump to') }}
      should-run-unit-tests: true
      should-notify-on-failure: true
      should-unzip-editor: true
      should-install-timeout-macos: true
      editor-binary-workflow: macos_builds.yml
      editor-binary-download: MirrorGodotEditorMac.app.zip
      editor-binary-name: MirrorGodotEditorMac.app/Contents/MacOS/Godot
      editor-binary-branch: dev
      editor-template-directory: ~/Library/Application\ Support/Godot/export_templates/4.3.dev
      template-binary-workflow: macos_builds.yml
      template-binary-name: macos_template.app.zip
      template-binary-branch: dev
      export-template-file: macos.zip
      game-environment-cfg-name: dev
      game-export-preset: MacOS-themirror-dev
      game-binary-name: The Mirror Dev.app
      bucket-name: mirror_native_client_builds/AutoUpdater
      os: "macOS"
      environment: dev
      url: https://dev-api.themirror.space/storage/clients
      itch-project-name: dev-the-mirror
      platform-file-extension: .zip

  build-linux-server:
    name: Linux Game Server
    uses: ./.github/workflows/client-build-tool.yml
    secrets:
      gcp-secret: ${{ secrets.GCP_TOKEN_BUCKET }}
      cicd-token-github: ${{ secrets.CI_TOKEN_GITHUB }}
    with:
      should-deploy: false
      should-deploy-as-server: ${{ contains(github.event.head_commit.message, 'version bump to') }}
      should-run-unit-tests: true
      should-notify-on-failure: true
      editor-binary-workflow: linux_builds.yml
      editor-binary-name: MirrorGodotEditorLinux.x86_64
      editor-binary-download: MirrorGodotEditorLinux.x86_64
      editor-binary-branch: dev
      editor-template-directory: ~/.local/share/godot/export_templates/4.3.dev
      template-binary-workflow: linux_builds.yml
      template-binary-name: linux_release.x86_64
      template-binary-branch: dev
      export-template-file: linux_release.x86_64
      game-environment-cfg-name: dev
      game-export-preset: LinuxServer
      game-binary-name: mirror-server.x86_64
      server-pck-path: mirror-server.pck
      bucket-name: mirror_server_builds/AutomatedServerBuilds
      os: "Linux"
      environment: dev
  deploy-change-macos:
    name: "deploy to itch.io"
    if: ${{ contains(github.event.head_commit.message, 'version bump to') }}
    needs: [build-linux, build-windows, build-macos, build-linux-server]
    uses: the-mirror-megaverse/mirror-godot-app/.github/workflows/itch-deploy.yml@dev
    with:
      url: ${{ needs.build-macos.outputs.url }}
      file-name:  ${{ needs.build-macos.outputs.file-name }}
      version: ${{ needs.build-macos.outputs.version }}
      itch-project-name: dev-the-mirror
      user-name: themirrorgdp
    secrets:
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
  deploy-change-windows:
    name: "deploy to itch.io"
    if: ${{ contains(github.event.head_commit.message, 'version bump to') }}
    needs: [build-linux, build-windows, build-macos, build-linux-server]
    uses: the-mirror-megaverse/mirror-godot-app/.github/workflows/itch-deploy.yml@dev
    with:
      url: ${{ needs.build-windows.outputs.url }}
      file-name:  ${{ needs.build-windows.outputs.file-name }}
      version: ${{ needs.build-windows.outputs.version }}
      itch-project-name: dev-the-mirror
      user-name: themirrorgdp
    secrets:
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
  deploy-change-linux:
    name: "deploy to itch.io"
    if: ${{ contains(github.event.head_commit.message, 'version bump to') }}
    needs: [build-linux, build-windows, build-macos, build-linux-server]
    uses: the-mirror-megaverse/mirror-godot-app/.github/workflows/itch-deploy.yml@dev
    with:
      url: ${{ needs.build-linux.outputs.url }}
      file-name:  ${{ needs.build-linux.outputs.file-name }}
      version: ${{ needs.build-linux.outputs.version }}
      itch-project-name: dev-the-mirror
      user-name: themirrorgdp
    secrets:
      ITCH_IO_CICD: ${{ secrets.ITCH_IO_CICD }}
  activate-mirror-server-gd-server-version:
    name: "Activating mirror-server"
    if: ${{ contains(github.event.head_commit.message, 'version bump to') }}
    uses: the-mirror-megaverse/mirror-godot-app/.github/workflows/gd-server-version-deploy.yml@dev
    needs: [build-linux, build-windows, build-macos, deploy-change-linux, deploy-change-windows, deploy-change-macos, build-linux-server]
    with:
      url: 'https://dev-api.themirror.space/'
      version: ${{ needs.build-linux.outputs.version }}
    secrets:
      WSS_TOKEN: ${{ secrets.WSS_TOKEN_DEV }}
