name: 📊 Static Checks
on: push

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ["self-hosted", "Linux"]
    steps:
      - uses: actions/checkout@v3
      - name: File formatting checks (file_format.sh)
        run: |
          bash ./.github/scripts/file_format.sh
